// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Newtonsoft.Json;
using PetID.ImageClassification;
using PetID.ImageClassificationML.Model;

namespace PetID.ImageClassificationML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"T:\FPT\STUDY\SUMMER2020\PRX\Project\PetID\PetID.ImageClassification\PetID.ImageClassificationML.ConsoleApp\Data\data.tsv";
        private const string DATA_TRAINING_PATH = @"T:\FPT\STUDY\SUMMER2020\PRX\Project\PetID\PetID.ImageClassification\PetID.ImageClassificationML.ConsoleApp\Data\training\";

        static void Main(string[] args)
        {
            CreateModel();
        }

        static void PrepareDataFile()
        {
        }

        static void CreateModel()
        {
            //Preprocessor.ResizeAll(DATA_TRAINING_PATH, true);
            //Preprocessor.DeleteAllRaw(DATA_TRAINING_PATH, true);
            //Preprocessor.FlipAll(DATA_TRAINING_PATH, true);
            Preprocessor.LoadDatasetAndSaveToTsv(new[] { "Label", "ImageSource" },
                DATA_TRAINING_PATH, DATA_FILEPATH);
            ModelBuilder.CreateModel(DATA_FILEPATH);
        }

        static void TestConsumeModel()
        {
            var model = new ConsumeModel("MLModel.zip");
            var output = model.Predict(new ModelInput
            {
                ImageRaw = File.ReadAllBytes(
                    @"T:\FPT\STUDY\SUMMER2020\PRX\Project\PetID\PetID.ImageClassification\PetID.ImageClassificationML.ConsoleApp\Data\test\2.jpg")
            });
            Console.WriteLine(JsonConvert.SerializeObject(output));
        }
    }
}
