// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Newtonsoft.Json;
using PetID.ImageClassificationML.Model;

namespace PetID_ImageClassificationML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"Data/data.tsv";

        static void Main(string[] args)
        {
            //Create MLModel
            //ModelBuilder.CreateModel();

            //Consume
            var model = new ConsumeModel("MLModel.zip");
            var output = model.Predict(new ModelInput
            {
                ImageRaw = File.ReadAllBytes(
                    @"T:\FPT\STUDY\SUMMER2020\PRX\Project\PetID\PetID.ImageClassification\PetID.ImageClassificationML.ConsoleApp\Data\test\2.jpg")
            });
            Console.WriteLine(JsonConvert.SerializeObject(output));
        }
    }
}
