// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;

namespace PetID.ImageClassificationML.Model
{
    public class ConsumeModel
    {
        private readonly PredictionEngine<ModelInput, ModelOutput> _predictionEngine;
        public ConsumeModel(string modelPath)
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();
            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            _predictionEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public ModelOutput Predict(ModelInput input)
        {
            // Use model to make prediction on input data
            ModelOutput result = _predictionEngine.Predict(input);
            return result;
        }
    }
}
