// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using Microsoft.ML.Data;
using Newtonsoft.Json;

namespace PetID.ImageClassificationML.Model
{
    public class ModelOutput
    {
        // ColumnName attribute is used to change the column name from
        // its default value, which is the name of the field.
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }
        public float[] Score { get; set; }
    }


    [XmlRoot("modelOutput")]
    public class ModelOutputViewModel
    {
        [XmlElement("prediction")]
        [JsonProperty("prediction")]
        public string Prediction { get; set; }
        [XmlArray("topOutputs")]
        [XmlArrayItem("topOutput")]
        [JsonProperty("top_outputs")]
        public List<TopOutput> TopOutputs { get; set; }
    }

    [XmlRoot("topOutput")]
    public class TopOutput
    {
        [XmlElement("label")]
        public string Label { get; set; }
        [XmlElement("score")]
        public float Score { get; set; }
    }
}
