// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;
using Newtonsoft.Json;

namespace PetID.ImageClassificationML.Model
{
    public class ModelOutput
    {
        // ColumnName attribute is used to change the column name from
        // its default value, which is the name of the field.
        [JsonProperty("prediction")]
        [ColumnName("PredictedLabel")]
        public String Prediction { get; set; }
        [JsonProperty("score")]
        public float[] Score { get; set; }
    }
}
