// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace PetID.ImageClassificationML.Model
{
    public class ModelInput : TraningModel
    {
        public byte[] ImageRaw { get; set; }
    }
}
