// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using Microsoft.ML.Data;
using Newtonsoft.Json;

namespace PetID.ImageClassificationML.Model
{
    public class ModelOutput
    {
        // ColumnName attribute is used to change the column name from
        // its default value, which is the name of the field.
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }
        public float[] Score { get; set; }
    }

    public class ModelOutputViewModel
    {
        [JsonProperty("prediction")]
        public string Prediction { get; set; }
        [JsonProperty("top_outputs")]
        public IEnumerable<TopOutput> TopOutputs { get; set; }
    }

    public class TopOutput
    {
        public string Label { get; set; }
        public float Score { get; set; }
    }
}
